language: c

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - libsnappy1
    - libsnappy-dev
    - libleveldb-dev
    - librrd-dev
    - libxslt1-dev

before_install:
  - sudo apt-get -y install python2.7/trusty python2.7-dev/trusty python2.7-minimal/trusty libpython2.7/trusty libpython2.7-dev/trusty libpython2.7-minimal/trusty libpython2.7-stdlib/trusty
  - dpkg -l | grep python
  - which python
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo -H python get-pip.py

install:
  # - pip install -r requirements.txt
  # - pip install -r requirements-web.txt
  - sudo -H pip install -r requirements-dev.txt

script:
  - /usr/bin/env python -V
  - platter build -r requirements-web.txt

deploy:
  provider: s3
  access_key_id: "$S3_ACCESS_KEY"
  secret_access_key: "$S3_SECRET_ACCESS_KEY"
  bucket: "minemeld"
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  on:
    tags: true

after_deploy:
    - "export FILENAME=minemeld-core-$TRAVIS_TAG-linux-x86_64.tar.gz"
    - "export MD5SUM=$(md5sum dist/$FILENAME | awk '{ print $1 }')"
    - "export SHA256SUM=$(sha256sum dist/$FILENAME | awk '{ print $1 }')"
    - 'curl -i -f "https://$MINEMELD_AUTOUPDATE_API_HOST/beta/package?file=$FILENAME&version=$TRAVIS_TAG&md5=$MD5SUM&sha256=$SHA256SUM&package=minemeld-core" -H "x-api-key: $MINEMELD_AUTOUPDATE_API_KEY"'
