language: python
python:
  - "2.7"

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - libleveldb1
    - libsnappy1
    - libsnappy-dev
    - libleveldb-dev
    - librrd-dev
    - libxslt1-dev

install:
  - pip install -r requirements.txt
  - pip install -r requirements-web.txt

script:
  - true
