fabric:
  class: mixerwagon.fabric.AMQP
  args: {}

FTs:
  inboundaggregator:
    args: {}
    class: mixerwagon.ft.op.AggregateFT
    inputs:
      - blocklist_de_pop3
      - dshield_blocklist
      - blocklist_de_mail
      - virbl_dnsbl
      - spamhaus_DROP
      - spamhaus_EDROP
      - malwaredomainlist
      - openbl_base90
      - ET_compromisediplist
      - bruteforceblocker
    output: true
  inboundredis:
    args: {}
    class: mixerwagon.ft.redis.RedisSet
    inputs:
      - inboundaggregator
    output: false
  outboundredis:
    args: {}
    class: mixerwagon.ft.redis.RedisSet
    inputs:
      - outboundaggregator
    output: false
  outboundaggregator:
    args: {}
    class: mixerwagon.ft.op.AggregateFT
    inputs:
      - malc0de_ipbl
      - zeustracker_badips
    output: true
  blocklist_de_mail:
    args:
      source_name: blocklist.de/mail
      attributes:
        mw$application: smtp
        mw$direction: inbound
        mw$type: IPv4
      url: http://www.blocklist.de/lists/mail.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  blocklist_de_pop3:
    args:
      source_name: blocklist.de/pop3
      attributes:
        mw$application: pop3
        mw$direction: inbound
        mw$type: IPv4
      url: http://www.blocklist.de/lists/pop3.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  dshield_blocklist:
    args:
      interval: 3600
    class: mixerwagon.ft.dshield.DshieldBlockList
    output: true
  malc0de_ipbl:
    args:
      source_name: malc0de.com/bl
      attributes:
        mw$direction: outbound
        mw$type: IPv4
      cchar: "//"
      url: http://malc0de.com/bl/IP_Blacklist.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  virbl_dnsbl:
    args:
      source_name: virbl.org/dnsbl
      attributes:
        mw$application: smtp
        mw$direction: inbound
        mw$type: IPv4
      cchar: E
      url: http://virbl.org/download/virbl.dnsbl.bit.nl.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  zeustracker_badips:
    args:
      source_name: zeustracker.abuse.ch/badips
      attributes:
        mw$type: IPv4
        mw$direction: outbound
      cchar: "#"
      url: https://zeustracker.abuse.ch/blocklist.php?download=badips
    class: mixerwagon.ft.http.HttpFT
    output: true
  zeustracker_baddomains:
    args:
      source_name: zeustracker.abuse.ch/baddomains
      attributes:
        mw$type: domain
        mw$direction: outbound
      cchar: "#"
      url: https://zeustracker.abuse.ch/blocklist.php?download=baddomains
    class: mixerwagon.ft.http.HttpFT
    output: true
  spamhaus_DROP:
    args:
      source_name: www.spamhaus.org/drop/drop.txt
      attributes:
        mw$type: IPv4
        mw$direction: inbound
      cchar: ;
      split_char: ;
      url: http://www.spamhaus.org/drop/drop.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  spamhaus_EDROP:
    args:
      source_name: www.spamhaus.org/drop/edrop.txt
      attributes:
        mw$type: IPv4
        mw$direction: inbound
      cchar: ;
      split_char: ;
      url: http://www.spamhaus.org/drop/edrop.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  openbl_base90:
    args:
      source_name: www.openbl.org/lists/base.txt
      attributes:
        mw$type: IPv4
        mw$direction: inbound
      cchar: "#"
      url: http://www.openbl.org/lists/base.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  malwaredomainlist:
    args:
      source_name: www.malwaredomainlist.com/hostslist/ip.txt
      attributes:
        mw$type: IPv4
        mw$direction: inbound
      url: http://www.malwaredomainlist.com/hostslist/ip.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  ET_compromisediplist:
    args:
      source_name: http://rules.emergingthreats.net/open/suricata/rules/compromised-ips.txt
      attributes:
        mw$type: IPv4
        mw$direction: inbound
      url: http://rules.emergingthreats.net/open/suricata/rules/compromised-ips.txt
    class: mixerwagon.ft.http.HttpFT
    output: true
  bruteforceblocker:
    args:
      source_name: bruteforceblocker
      url: http://danger.rulez.sk/projects/bruteforceblocker/blist.php
      cchar: "#"
      split_char: "#"
      attributes:
        mw$type: IPv4
        mw$direction: inbound
    class: mixerwagon.ft.http.HttpFT
    output: true


